#!/bin/bash

geany helloSoup.py helloReference.py scoutEmOut.py amTheStrobe.py marchSpartaness.py unlimitedData.py strobePlayerUnique.py obfuscant.py gitter ../soupyFlow.txt  &
## got tired of doing this manually every time with geany

exit 0
