#!/bin/bash

geany helloSoup.py helloReference.py scoutEmOut.py amTheStrobe.py marchSpartaness.py unlimitedData.py strobePlayerUnique.py obfuscant.py dictool.py finalMerge.py strobePlayerAnalysis.py ../soupyFlow.txt gitter  &
## got tired of doing this manually every time with geany

exit 0
