#!/bin/bash

## do all the things...

python readata.py watMu beginner Linear>./logs/beginner.txt
sleep 300
python readata.py watMu intermediate Linear>./logs/intermediate.txt
sleep 300
python readata.py watMu advanced Linear>./logs/advanced.txt
sleep 300
python readata.py watMu allstar Linear>./logs/allstar.txt
sleep 300

python readata.py nhl everything Linear>./logs/everything.txt
sleep 300
python readata.py nhl originalSix Linear>./logs/originalSix.txt
sleep 300
python readata.py nhl earlyNhl Linear>./logs/earlyNhl.txt
sleep 300
python readata.py nhl postLockout Linear>./logs/postLockout.txt
## this should take about a month on a dual core machine...

exit 0
