#!/bin/bash

## do all the things...

python readata.py watMu beginner Multithread>./logs/beginner.txt
sleep 300
python readata.py watMu intermediate Multithread>./logs/intermediate.txt
sleep 300
python readata.py watMu advanced Multithread>./logs/advanced.txt
sleep 300
python readata.py watMu allstar Multithread>./logs/allstar.txt
sleep 300

python readata.py nhl everything Multithread>./logs/everything.txt
sleep 300
python readata.py nhl originalSix Multithread>./logs/originalSix.txt
sleep 300
python readata.py nhl earlyNhl Multithread>./logs/earlyNhl.txt
sleep 300
python readata.py nhl postLockout Multithread>./logs/postLockout.txt
## this should take about a month on a dual core machine...

exit 0
