#!/bin/bash

## do all the things...

python readata.py watMu beginner>./logs/beginner.txt
sleep 300
python readata.py watMu intermediate>./logs/intermediate.txt
sleep 300
python readata.py watMu advanced>./logs/advanced.txt
sleep 300
python readata.py watMu allstar>./logs/allstar.txt
sleep 300

python readata.py nhl everything>./logs/everything.txt
sleep 300
python readata.py nhl originalSix>./logs/originalSix.txt
sleep 300
python readata.py nhl earlyNhl>./logs/earlyNhl.txt
sleep 300
python readata.py nhl postLockout>./logs/postLockout.txt
## this should take about a month on a dual core machine...

exit 0
