#!/bin/bash

geany doorBreach.py webScrewdriver.py imlTeamProcessing.py teamSpider.py teamRaw.py imSurfer.py fall2016hooks.csv spynMeRound.py gitter ../soupyFlow.txt  &
## got tired of doing this manually every time with geany

exit 0
